<?php
/**
 * Template for block Klec_Rotate_Block_Form_Gallery
 */
?>
<?php
$_block = $this;
/* @var $_block Mage_Adminhtml_Block_Catalog_Product_Helper_Form_Gallery_Content */
?>
<div id="<?php echo $_block->getHtmlId() ?>" >
    <div class="grid">
        <div style="text-align: center">
            <img id="big_img" src="" width="500" alt="sample">
        </div>
        <div id="block_images"  style="position: relative; height: 152px;"></div>
        <?php //echo $_block->getUploaderHtml() ?>
        <?php echo $_block->getUploaderHtml() ?>
    </div>
</div>
<input type="hidden" id="<?php echo $_block->getHtmlId() ?>_save" name="<?php echo $_block->getElement()->getName() ?>[images]" value="<?php echo $_block->htmlEscape($_block->getImagesJson()) ?>" />
<input type="hidden" id="<?php echo $_block->getHtmlId() ?>_save_image" name="<?php echo $_block->getElement()->getName() ?>[values]" value="<?php echo $_block->htmlEscape($_block->getImagesValuesJson()) ?>" />
<script type="text/javascript">
var images = <?php echo $_block->getImagesJson() ?>;
var image_wraper = $('block_images');
var step = ($('page:main-container').measure('width')-330)/images.length;
var dragObject = {};
images.each(function(img,id){
    image_wraper.insert(
        new Element('img', {src: img.url, style:'height:150px; position:absolute; left:'+id*step+'px'})
            .observe('mouseover',function(){
                $('big_img').setAttribute('src',this.readAttribute('src'));
                this.style.zIndex = "10";
            }).observe('mouseout',function(){
                $('big_img').setAttribute('src',this.readAttribute('src'));
                this.style.zIndex = "1";
            }).observe('mousedown',function(e,id){

                dragObject = this;
                e = fixEvent(e);
                dragObject.downX = e.pageX;
                dragObject.id = getId(this);
                e.preventDefault ? e.preventDefault() : e.returnValue = false
            }).observe('mouseup',function(e){
                dragObject = {};
                order();
            }).observe('mousemove',function(e){
                e.preventDefault ? e.preventDefault() : e.returnValue = false
                if(dragObject == this){
                    e = fixEvent(e);
                    dragObject.style.left = parseInt(dragObject.style.left) + e.pageX - dragObject.downX + "px";
                    dragObject.downX = e.pageX;

                }
                // @todo check order
            })
    );
})
    if(images[0]){
        $('big_img').setAttribute('src',images[0].url);
    }
images = $$('#block_images IMG');

function fixEvent(e) {
            e = e || window.event

    	    if ( e.pageX == null && e.clientX != null ) {
    	        var html = document.documentElement
                var body = document.body
                e.pageX = e.clientX +
                    (html && html.scrollLeft || body && body.scrollLeft || 0) -
                    (html.clientLeft || 0);

            }
            return e
    	}

function order() {
    images.each(function(img, id){
        if(images[id-1] && parseInt(images[id].style.left)<parseInt(images[id-1].style.left)){
            temp = images[id];
            images[id] = images[id-1];
            images[id-1] = temp;
        }
    })
    images.each(function(img, id){
        img.style.left = id*step + "px";
    })
}

function getId(valeur) {
    for (var i in images) { if (images[i] === valeur) return i+1; }
    return 0;
}
</script>
