<?php
/**
 * Template for block Klec_Rotate_Block_Form_Gallery
 */
?>
<?php
$_block = $this;
/* @var $_block Mage_Adminhtml_Block_Catalog_Product_Helper_Form_Gallery_Content */
?>
<div id="<?php echo $_block->getHtmlId() ?>" >
    <div class="grid">
        <div style="text-align: center">
            <img id="big_img" src="" width="500" alt="sample">
        </div>
        <div id="block_images"  style="position: relative; height: 152px;"></div>
        <?php //echo $_block->getUploaderHtml() ?>
        <form action="" method="post">
            <input name="files" type="file" multiple />
            <input type="submit"></submit>
        </form>
    </div>
</div>
<input type="hidden" id="<?php echo $_block->getHtmlId() ?>_save" name="<?php echo $_block->getElement()->getName() ?>[images]" value="<?php echo $_block->htmlEscape($_block->getImagesJson()) ?>" />
<input type="hidden" id="<?php echo $_block->getHtmlId() ?>_save_image" name="<?php echo $_block->getElement()->getName() ?>[values]" value="<?php echo $_block->htmlEscape($_block->getImagesValuesJson()) ?>" />
<script type="text/javascript">
var images = <?php echo $_block->getImagesJson() ?>;
var image_wraper = $('block_images');
var step = ($('page:main-container').measure('width')-330)/images.length;
images.each(function(img,id){
    image_wraper.insert(
        new Element('img', {src: img.url, style:'height:150px; position:absolute; left:'+id*step+'px'})
            .observe('mouseover',function(){
                $('big_img').setAttribute('src',this.readAttribute('src'))
            })
    );
})
    if(images[0]){
        $('big_img').setAttribute('src',images[0].url)
    }
</script>
