<?php
/**
 * Template for block Klec_Rotate_Block_Form_Gallery
 */
$_block = $this;
/* @var $_block Mage_Adminhtml_Block_Catalog_Product_Helper_Form_Gallery_Content */
?>
<div id="<?php echo $_block->getHtmlId() ?>">
    <div class="grid">
        <div style="text-align: center">
            <img id="big_img" src="" width="500" alt="sample">
        </div>
        <div  id="image_scroller" class="hor-scroll" style="height: 170px; margin-bottom: 10px;">
            <div  id="<?php echo $_block->getHtmlId() ?>_list" class="image_wrapper" style="position: relative; height: 152px;">
                <span src="" id="<?php echo $_block->getHtmlId() ?>_template" class="template no-display" alt=""/>
            </div>
        </div>
        <?php echo $_block->getUploaderHtml() ?>
    </div>
</div>
<input type="hidden" id="<?php echo $_block->getHtmlId() ?>_save"
       name="<?php echo $_block->getElement()->getName() ?>[images]"
       value="<?php echo $_block->htmlEscape($_block->getImagesJson()) ?>"/>
<input type="hidden" id="<?php echo $_block->getHtmlId() ?>_save_image"
       name="<?php echo $_block->getElement()->getName() ?>[values]"
       value="<?php echo $_block->htmlEscape($_block->getImagesValuesJson()) ?>"/>
<script type="text/javascript">
    var images = <?php echo $_block->getImagesJson() ?>;
    var image_wraper = $('<?php echo $_block->getHtmlId() ?>_list');
    var step = 150;
    var dragObject = {};
    var <?php echo $_block->getJsObjectName(); ?> = new RotateGallery('<?php echo $_block->getHtmlId() ?>', <?php echo $_block->getUploader()->getJsObjectName() ?>, <?php echo $_block->getImageTypesJson() ?>);
    if (images[0]) {
        $('big_img').setAttribute('src', images[0].url);
    }

</script>
